import json
from os.path import join
from collections import defaultdict
from snakemake.utils import validate


validate(config, "../config/config.schema.yaml")


OUTPUT_DIR = config["output_dir"]
LOG_DIR = config["logs_dir"]
CLEANUP_TEMPFILES = config.get("cleanup_tempfiles", True)
MIN_READ_LENGTH = config["min_read_length"]
MIN_MAPQ = config["min_mapq"]

# {sm: {'treatment': {'name': str, 'reads': list[str] }, 'control': ... , 'asm_fa': str}}
SAMPLES = defaultdict(lambda: defaultdict(dict))
WC_SAMPLES = []
WC_GROUP = []
for sm_cfg in config["samples"]:
    sample_name = sm_cfg["name"]
    SAMPLES[sample_name]["asm_fa"] = sm_cfg["asm_fa"]
    SAMPLES[sample_name]["bed"] = sm_cfg["bed"]
    SAMPLES[sample_name]["tracks"] = sm_cfg.get("tracks", {})
    SAMPLES[sample_name]["cfg_cenplot"] = sm_cfg.get("cfg_cenplot")

    for grp in ["treatment", "control"]:
        SAMPLES[sample_name][grp]["group"] = sm_cfg[grp]["name"]
        SAMPLES[sample_name][grp]["reads"] = sm_cfg[grp]["reads"]
        WC_SAMPLES.append(sample_name)
        WC_GROUP.append(grp)


wildcard_constraints:
    sm="|".join(WC_SAMPLES),
    grp="|".join(WC_GROUP),


FILTERED_ALN_SM_CONFIG = []
for sm, sm_cfg in SAMPLES.items():
    for grp in ("treatment", "control"):
        FILTERED_ALN_SM_CONFIG.append(
            {
                "name": f"{sm}_{grp}",
                "asm_fa": sm_cfg["asm_fa"],
                "reads": sm_cfg[grp]["reads"],
                "min_read_length": MIN_READ_LENGTH,
            }
        )

# Don't keep samples.
config.pop("samples")


module Align:
    snakefile:
        "rules/Snakemake-Aligner/workflow/Snakefile"
    config:
        {"samples": FILTERED_ALN_SM_CONFIG, **config}


use rule * from Align


rule filter_by_mapq:
    input:
        bam=expand(rules.merge_read_asm_alignments.output.alignment, sm="{sm}_{grp}"),
    output:
        bam=join(OUTPUT_DIR, f"{{sm}}_{{grp}}_min_mapq_{MIN_MAPQ}.bam"),
        bai=join(OUTPUT_DIR, f"{{sm}}_{{grp}}_min_mapq_{MIN_MAPQ}.bam.bai"),
    conda:
        "envs/env.yaml"
    params:
        min_mapq=MIN_MAPQ,
    log:
        os.path.join(LOG_DIR, "filter_by_mapq_{sm}_{grp}.log"),
    threads: config["threads_pileup"]
    shell:
        """
        samtools view -bh \
        -q {params.min_mapq} \
        -o {output.bam} \
        -@ {threads} \
        {input.bam} 2> {log}
        samtools index {output.bam} 2>> {log}
        """


rule pileup_m6a:
    input:
        bam=(
            expand(rules.merge_read_asm_alignments.output.alignment, sm="{sm}_{grp}")
            if MIN_MAPQ == 0
            else rules.filter_by_mapq.output.bam
        ),
        fa=expand(rules.merge_asm_files.output.asm, sm="{sm}_{grp}"),
        bed=lambda wc: SAMPLES[wc.sm]["bed"],
    output:
        bed=join(OUTPUT_DIR, "{sm}_{grp}.bed.gz"),
    params:
        motif="AT 0",
        filter_threshold=config["filter_threshold"],
    conda:
        "envs/env.yaml"
    threads: config["threads_pileup"]
    log:
        os.path.join(LOG_DIR, "pileup_m6a_{sm}_{grp}.log"),
    shell:
        """
        samtools faidx {input.fa} 2> {log}
        {{ modkit pileup \
            {input.bam} \
            - \
            --ref {input.fa} \
            --include-bed {input.bed} \
            -t {threads} \
            --motif {params.motif} \
            --filter-threshold {params.filter_threshold} | \
            sort -k1,1 -k2,2n | \
            bgzip ;}} > {output.bed} 2>> {log}
        tabix -p bed {output.bed} 2>> {log}
        """


rule dmr_pair:
    input:
        fa=expand(rules.merge_asm_files.output.asm, sm="{sm}_control"),
        control_bed=lambda wc: expand(
            rules.pileup_m6a.output,
            sm=wc.sm,
            grp="control",
        ),
        treatment_bed=lambda wc: expand(
            rules.pileup_m6a.output,
            sm=wc.sm,
            grp="treatment",
        ),
    output:
        bed=join(OUTPUT_DIR, "{sm}_dmr.bed.gz"),
    params:
        motif="--base A --base T",
    conda:
        "envs/env.yaml"
    threads: config["threads_pileup"]
    log:
        os.path.join(LOG_DIR, "dmr_pair_{sm}.log"),
    shell:
        """
        modkit dmr pair \
        --ref {input.fa} \
        -a {input.control_bed} \
        -b {input.treatment_bed} \
        {params.motif} \
        --log-filepath {log} | \
        sort -k1,1 -k2,2n | \
        bgzip > {output.bed}
        """


rule filter_dmr_pair:
    input:
        rules.dmr_pair.output,
    output:
        bed=join(OUTPUT_DIR, "{sm}_dmr_filter_merge.bed.gz"),
    conda:
        "envs/env.yaml"
    params:
        # https://nanoporetech.github.io/modkit/dmr_scoring_details.html
        lt_cohen_h=-3.1,
        gt_cohen_h_lower_bound=0.8,
    shell:
        """
        {{ zcat {input} | \
        awk '$17 < {params.lt_cohen_h} && $18 > {params.gt_cohen_h_lower_bound}' | \
        sort -k1,1 -k2,2n | \
        cut -f1-3 | \
        bedtools merge -i - -d 5000 | \
        bgzip ;}} > {output.bed}
        tabix -p bed {output.bed}
        """


rule intersect_tracks:
    input:
        tracks=lambda wc: SAMPLES[wc.sm]["tracks"].values(),
        bed=lambda wc: SAMPLES[wc.sm]["bed"],
    output:
        temp(os.path.join(OUTPUT_DIR, "intersect_tracks_{sm}.fofn")),
    conda:
        "envs/env.yaml"
    shell:
        """
        if [ -z "{input.tracks}" ]; then
            exit 0
        fi
        for infile in {input.tracks}; do
            outfile="${{infile}}.{wildcards.sm}.tmp"
            bedtools intersect -a <(zcat -f ${{infile}}) -b {input.bed} > ${{outfile}}
            echo ${{outfile}} >> {output}
        done
        """


rule generate_coverage_tracks:
    input:
        control_bed=lambda wc: expand(
            rules.pileup_m6a.output,
            sm=wc.sm,
            grp="control",
        ),
        treatment_bed=lambda wc: expand(
            rules.pileup_m6a.output,
            sm=wc.sm,
            grp="treatment",
        ),
    output:
        bg_cov_ctrl=join(OUTPUT_DIR, "{sm}_ctrl_cov.bg.gz"),
        bg_cov_treatment=join(OUTPUT_DIR, "{sm}_treatment_cov.bg.gz"),
    conda:
        "envs/env.yaml"
    shell:
        """
        # https://nanoporetech.github.io/modkit/intro_pileup.html#bedmethyl-column-descriptions
        zcat {input.control_bed} | cut -f1-3,10 | bgzip > {output.bg_cov_ctrl}
        zcat {input.treatment_bed} | cut -f1-3,10 | bgzip > {output.bg_cov_treatment}
        """


def json_tracks(wc, input) -> str:
    tracks = {
        '"dmr"': f'"{input.dmr[0]}"',
        '"cov_treatment"': f'"{input.cov_treatment_bg}"',
        '"cov_ctrl"': f'"{input.cov_control_bg}"',
    }
    if input.tracks_intersect:
        for dtype, track in SAMPLES[wc.sm]["tracks"].items():
            tracks[f'"{dtype}"'] = f'"{track}.{wc.sm}.tmp"'
    return f'-j "{json.dumps(tracks)}"'


rule draw_plot:
    input:
        # modkit pileups
        control_bed=lambda wc: expand(
            rules.pileup_m6a.output,
            sm=wc.sm,
            grp="control",
        ),
        treatment_bed=lambda wc: expand(
            rules.pileup_m6a.output,
            sm=wc.sm,
            grp="treatment",
        ),
        # Bedgraph tracks.
        cov_treatment_bg=rules.generate_coverage_tracks.output.bg_cov_treatment,
        cov_control_bg=rules.generate_coverage_tracks.output.bg_cov_ctrl,
        # Differntially methylated regions.
        dmr=rules.filter_dmr_pair.output,
        # Tracks to add
        tracks_intersect=lambda wc: (
            rules.intersect_tracks.output if SAMPLES[wc.sm]["tracks"] else []
        ),
        # Configuration file for cenplot.
        # If track in json_tracks not listed, ignored.
        cfg_cenplot=lambda wc: SAMPLES[wc.sm].get("cfg_cenplot", []),
    output:
        plot_dir=directory(join(OUTPUT_DIR, "plots", "{sm}")),
    params:
        script=workflow.source_path("scripts/plot_enrichment.py"),
        window=config["window_size"],
        mode=config["mode"],
        json_tracks=lambda wc, input: json_tracks(wc, input),
        cfg_cenplot=lambda wc, input: (
            f"--base_cenplot_cfg {input.cfg_cenplot}" if input.cfg_cenplot else ""
        ),
        cmd_cleanup=lambda wc, input: (
            f"cat {input.tracks_intersect} | xargs rm -f"
            if SAMPLES[wc.sm]["tracks"] and CLEANUP_TEMPFILES
            else "echo 'No tracks or not cleaning up tempfiles.'"
        ),
    log:
        os.path.join(LOG_DIR, "draw_plot_{sm}.log"),
    conda:
        "envs/env.yaml"
    shell:
        """
        # https://nanoporetech.github.io/modkit/intro_pileup.html#bedmethyl-column-descriptions
        python {params.script} \
        -t <(zcat {input.treatment_bed} | cut -f1-3,11) \
        -c <(zcat {input.control_bed} | cut -f1-3,11) \
        -w {params.window} \
        -o {output.plot_dir} \
        -m {params.mode} \
        {params.json_tracks} {params.cfg_cenplot} 2> {log}
        {{ {params.cmd_cleanup} ;}} &>> {log}
        """


rule all:
    input:
        expand(
            rules.pileup_m6a.output,
            zip,
            sm=WC_SAMPLES,
            grp=WC_GROUP,
        ),
        expand(rules.dmr_pair.output, sm=WC_SAMPLES),
        expand(
            rules.draw_plot.output,
            zip,
            sm=WC_SAMPLES,
        ),
    default_target: True
