$schema: "https://json-schema.org/draft/2020-12/schema"
properties:
  min_read_length:
    type: integer
    default: 0
  window_size:
    type: integer
    default: 5000
  threads_pileup:
    type: integer
    default: 1
  mode:
    type: string
    enum: [ratio, diff]
    default: diff
    description: Mode to compare difference between treatment and control.
  filter_threshold:
    type: number
    default: 0.95
    description: Pileup threshold for modkit pileup.
  min_mapq:
    type: integer
    default: 0
    minimum: 0
    maximum: 60
  cleanup_tempfiles:
    type: boolean
    default: true
    description: Cleanup intersected BED files, if any.
  samples:
    type: array
    items:
      type: object
      additionalProperties: false
      properties:
        name:
          type: string
          description: Name of sample.
        asm_fa:
          type: string
          description: Assembly to align DiMeLo-seq reads against.
        bed:
          type: string
          description: BED file of regions to visualize.
        tracks:
          type: object
          description: Tracks to plot. Each key should match the name of the path variable in the cenplot config. All BED files should have no header.
        cfg_cenplot:
          type: string
          default: config/base_cenplot.toml
          description: Base config file for cenplot.
        modification:
          type: string
          default: AT
          enum: ["AT", "CG"]
          description: "Which modification to use in pileup."
        treatment:
          type: object
          additionalProperties: false
          properties:
            name:
              type: string
              description: Name of treatment group.
            reads:
              type: array
              description: Reads for treatment group. Either fastq.gz or uBAM.
              items:
                type: string
        control:
          type: object
          additionalProperties: false
          properties:
            name:
              type: string
              description: Name of control group.
            reads:
              type: array
              description: Reads for control group. Either fastq.gz or uBAM.
              items:
                type: string
        required:
        - name
        - asm_fa
        - treatment
        - control
